name: CroApt Core Build

run-name: CroApt Core Build @${{ github.sha }}

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create CroApt Core Version Label]
    types:
      - completed
    branches:
      - master
      - epic/**
  pull_request:
    branches:
      - master
      - epic/**

jobs:
  label_check:
    if: ${{ github.event_name == 'pull_request' }}
    name: Pull Request Label Checker
    uses: sergey-koryshev/build-system/.github/workflows/pr-label-checker.yml@version-helper-v1.4.0
    with:
      version-configuration-path: version-configuration.json
      scripts-ref: version-helper-v1.4.0
  build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    name: CroApt Core Build
    uses: ./.github/workflows/build.yml
    with:
      node-version: 18.x
      lint-command: "npm run lint"
      build-command: "npm run build"
